# Generated by Django 3.0.6 on 2020-06-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Информация пользователя', 'verbose_name_plural': 'Информация пользователей'},
        ),
    ]
