# Generated by Django 3.0.9 on 2020-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_modeltask1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltask1',
            options={'verbose_name': 'task1', 'verbose_name_plural': 'task2'},
        ),
        migrations.AddField(
            model_name='modeltask1',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
