# Generated by Django 3.0.6 on 2020-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrations', '0003_auto_20200802_1530'),
        ('Profile', '0002_auto_20200612_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='to_do_list',
            field=models.ManyToManyField(to='Administrations.ToDoList'),
        ),
    ]
