# Generated by Django 3.0.9 on 2020-10-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201028_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask1',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modeltask1',
            name='fio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modeltask1',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modeltask1',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modeltask1',
            name='phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
