# Generated by Django 3.0.6 on 2020-08-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_to_do_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='to_do_list',
        ),
    ]
