# Generated by Django 3.0.9 on 2022-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201028_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelTask1',
        ),
    ]
