# Generated by Django 3.0.9 on 2020-08-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_number',
        ),
    ]
