# Generated by Django 3.0.6 on 2020-08-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_tags_number',
            new_name='comment_number',
        ),
    ]
