# Generated by Django 3.0.6 on 2020-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200808_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
