# Generated by Django 3.0.6 on 2020-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='tasks',
            new_name='task',
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
