# Generated by Django 3.0.6 on 2020-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrations', '0002_auto_20200802_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Cписок дел', 'verbose_name_plural': 'Cписок дел'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
