# Generated by Django 3.0.6 on 2020-08-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrations', '0005_livechatview_roomchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='roomchat',
            name='users',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomchat',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomchat',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Клиент', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomchat',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
