# Generated by Django 3.0.6 on 2020-08-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrations', '0006_auto_20200802_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechatview',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
