# Generated by Django 3.0.9 on 2020-09-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_time'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
