# Generated by Django 3.0.6 on 2020-08-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200810_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Products.Products'),
        ),
    ]
