# Generated by Django 3.0.6 on 2020-08-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_commentproduct_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Products.CommentProduct', verbose_name='Родитель'),
        ),
    ]
