# Generated by Django 3.0.6 on 2020-08-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_ratingproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Products.Products'),
        ),
    ]
